__version__ = ".2"

WARNING_BLURB = "This report was generated by VDM Version %s. This is development software." % __version__
    
HTMLREPORTHEAD = """<!DOCTYPE html> 
<html lang="en">
<head>
<title>%s</title>
<meta charset="utf-8" />
<link rel='stylesheet' href='http://www.caregraf.org/semanticvista/analytics/VOLDEMORT/voldemort.css' type='text/css'>
</head>
<body>
<div id="header">
<h1 id="logo">%s</h1>
</div>
<div id="reports">
"""

HTMLREPORTTAIL = """
</div><div id="footer">Generated using the <a href="https://github.com/OSEHR/VOLDEMORT">VOLDEMORT Framework</a> at %s</div>
</body>
</html>"""

